### ISSUE TITLE
Feature: User can delete a stock from the trending stocks container

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/stock-tracker#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a trending stock from the trending stocks view

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/82472092/121788986-e308e800-cb86-11eb-84b3-aa9f2c50fbe1.png)
![image](https://user-images.githubusercontent.com/82472092/121789001-f451f480-cb86-11eb-8fc9-cdb57cec3919.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make sure that when the plus icon is clicked, the plus icon changes to the X icon
- [x] Add an event listener to the X icon
- [x] When the X icon is clicked, get the data of the trending stock and store it in a variable
- [x] Loop through the watchlist property of the data model and find the matching stock
- [x] When the matching stock is found, remove that entry from the data model
- [x] Remove the stock from the document as well
- [x] Keep the view on trending stocks
- [x] Remove all unnecessary styling
- [x] Test all functionality
- [x] Fix all errors
