### ISSUE TITLE
Refactor: to ES6

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/stock-tracker#15]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] ... 
- [x] ...
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
